-- Complete national commune catalog from Chilean territorial data.
-- Existing legacy codes are kept for the first seeded records to preserve data.
insert into public.communes (code, name, province, region, is_active)
values
  ('15101', 'Arica', 'Arica', 'Arica y Parinacota'),
  ('15102', 'Camarones', 'Arica', 'Arica y Parinacota'),
  ('15201', 'Putre', 'Parinacota', 'Arica y Parinacota'),
  ('15202', 'General Lagos', 'Parinacota', 'Arica y Parinacota'),
  ('01101', 'Iquique', 'Iquique', 'Tarapacá'),
  ('01102', 'Alto Hospicio', 'Iquique', 'Tarapacá'),
  ('01201', 'Pozo Almonte', 'Tamarugal', 'Tarapacá'),
  ('01402', 'Camiña', 'Tamarugal', 'Tarapacá'),
  ('01403', 'Colchane', 'Tamarugal', 'Tarapacá'),
  ('01404', 'Huara', 'Tamarugal', 'Tarapacá'),
  ('01405', 'Pica', 'Tamarugal', 'Tarapacá'),
  ('02101', 'Antofagasta', 'Antofagasta', 'Antofagasta'),
  ('02102', 'Mejillones', 'Antofagasta', 'Antofagasta'),
  ('02103', 'Sierra Gorda', 'Antofagasta', 'Antofagasta'),
  ('02104', 'Taltal', 'Antofagasta', 'Antofagasta'),
  ('02201', 'Calama', 'El Loa', 'Antofagasta'),
  ('02202', 'Ollagüe', 'El Loa', 'Antofagasta'),
  ('02203', 'San Pedro de Atacama', 'El Loa', 'Antofagasta'),
  ('02301', 'Tocopilla', 'Tocopilla', 'Antofagasta'),
  ('02302', 'María Elena', 'Tocopilla', 'Antofagasta'),
  ('03101', 'Copiapó', 'Copiapó', 'Atacama'),
  ('03102', 'Caldera', 'Copiapó', 'Atacama'),
  ('03103', 'Tierra Amarilla', 'Copiapó', 'Atacama'),
  ('03201', 'Chañaral', 'Chañaral', 'Atacama'),
  ('03202', 'Diego de Almagro', 'Chañaral', 'Atacama'),
  ('03301', 'Vallenar', 'Huasco', 'Atacama'),
  ('03302', 'Alto del Carmen', 'Huasco', 'Atacama'),
  ('03303', 'Freirina', 'Huasco', 'Atacama'),
  ('03304', 'Huasco', 'Huasco', 'Atacama'),
  ('04101', 'La Serena', 'Elqui', 'Coquimbo'),
  ('co0102', 'Coquimbo', 'Elqui', 'Coquimbo'),
  ('04103', 'Andacollo', 'Elqui', 'Coquimbo'),
  ('04104', 'La Higuera', 'Elqui', 'Coquimbo'),
  ('04105', 'Paiguano', 'Elqui', 'Coquimbo'),
  ('04106', 'Vicuña', 'Elqui', 'Coquimbo'),
  ('04201', 'Illapel', 'Choapa', 'Coquimbo'),
  ('04202', 'Canela', 'Choapa', 'Coquimbo'),
  ('04203', 'Los Vilos', 'Choapa', 'Coquimbo'),
  ('04204', 'Salamanca', 'Choapa', 'Coquimbo'),
  ('04301', 'Ovalle', 'Limarí', 'Coquimbo'),
  ('04302', 'Combarbalá', 'Limarí', 'Coquimbo'),
  ('04303', 'Monte Patria', 'Limarí', 'Coquimbo'),
  ('04304', 'Punitaqui', 'Limarí', 'Coquimbo'),
  ('04305', 'Río Hurtado', 'Limarí', 'Coquimbo'),
  ('vs0101', 'Valparaíso', 'Valparaíso', 'Valparaíso'),
  ('05102', 'Casablanca', 'Valparaíso', 'Valparaíso'),
  ('05103', 'Concón', 'Valparaíso', 'Valparaíso'),
  ('05104', 'Juan Fernández', 'Valparaíso', 'Valparaíso'),
  ('05105', 'Puchuncaví', 'Valparaíso', 'Valparaíso'),
  ('05107', 'Quintero', 'Valparaíso', 'Valparaíso'),
  ('vs0109', 'Viña del Mar', 'Valparaíso', 'Valparaíso'),
  ('05201', 'Isla de Pascua', 'Isla de Pascua', 'Valparaíso'),
  ('05301', 'Los Andes', 'Los Andes', 'Valparaíso'),
  ('05302', 'Calle Larga', 'Los Andes', 'Valparaíso'),
  ('05303', 'Rinconada', 'Los Andes', 'Valparaíso'),
  ('05304', 'San Esteban', 'Los Andes', 'Valparaíso'),
  ('05401', 'La Ligua', 'Petorca', 'Valparaíso'),
  ('05402', 'Cabildo', 'Petorca', 'Valparaíso'),
  ('05403', 'Papudo', 'Petorca', 'Valparaíso'),
  ('05404', 'Petorca', 'Petorca', 'Valparaíso'),
  ('05405', 'Zapallar', 'Petorca', 'Valparaíso'),
  ('05501', 'Quillota', 'Quillota', 'Valparaíso'),
  ('05502', 'Calera', 'Quillota', 'Valparaíso'),
  ('05503', 'Hijuelas', 'Quillota', 'Valparaíso'),
  ('05504', 'La Cruz', 'Quillota', 'Valparaíso'),
  ('05506', 'Nogales', 'Quillota', 'Valparaíso'),
  ('05601', 'San Antonio', 'San Antonio', 'Valparaíso'),
  ('05602', 'Algarrobo', 'San Antonio', 'Valparaíso'),
  ('05603', 'Cartagena', 'San Antonio', 'Valparaíso'),
  ('05604', 'El Quisco', 'San Antonio', 'Valparaíso'),
  ('05605', 'El Tabo', 'San Antonio', 'Valparaíso'),
  ('05606', 'Santo Domingo', 'San Antonio', 'Valparaíso'),
  ('05701', 'San Felipe', 'San Felipe de Aconcagua', 'Valparaíso'),
  ('05702', 'Catemu', 'San Felipe de Aconcagua', 'Valparaíso'),
  ('05703', 'Llaillay', 'San Felipe de Aconcagua', 'Valparaíso'),
  ('05704', 'Panquehue', 'San Felipe de Aconcagua', 'Valparaíso'),
  ('05705', 'Putaendo', 'San Felipe de Aconcagua', 'Valparaíso'),
  ('05706', 'Santa María', 'San Felipe de Aconcagua', 'Valparaíso'),
  ('05801', 'Quilpué', 'Marga Marga', 'Valparaíso'),
  ('05802', 'Limache', 'Marga Marga', 'Valparaíso'),
  ('05803', 'Olmué', 'Marga Marga', 'Valparaíso'),
  ('05804', 'Villa Alemana', 'Marga Marga', 'Valparaíso'),
  ('06101', 'Rancagua', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06102', 'Codegua', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06103', 'Coinco', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06104', 'Coltauco', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06105', 'Doñihue', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06106', 'Graneros', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06107', 'Las Cabras', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06108', 'Machalí', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06109', 'Malloa', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06110', 'Mostazal', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06111', 'Olivar', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06112', 'Peumo', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06113', 'Pichidegua', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06114', 'Quinta de Tilcoco', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06115', 'Rengo', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06116', 'Requínoa', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06117', 'San Vicente', 'Cachapoal', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06201', 'Pichilemu', 'Cardenal Caro', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06202', 'La Estrella', 'Cardenal Caro', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06203', 'Litueche', 'Cardenal Caro', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06204', 'Marichihue', 'Cardenal Caro', 'Región del Libertador Gral. Bernardo O''Higgins'),
  ('06205', 'Navidad', 'Cardenal Caro', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06206', 'Paredones', 'Cardenal Caro', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06301', 'San Fernando', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06302', 'Chépica', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06303', 'Chimbarongo', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06304', 'Lolol', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06305', 'Nancagua', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06306', 'Palmilla', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06307', 'Peralillo', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06308', 'Placilla', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06309', 'Pumanque', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('06310', 'Santa Cruz', 'Colchagua', 'Región del Libertador Gral. Bernardo O’Higgins'),
  ('07101', 'Talca', 'Talca', 'Región del Maule'),
  ('07102', 'Constitución', 'Talca', 'Región del Maule'),
  ('07103', 'Curepto', 'Talca', 'Región del Maule'),
  ('07104', 'Empedrado', 'Talca', 'Región del Maule'),
  ('07105', 'Maule', 'Talca', 'Región del Maule'),
  ('07106', 'Pelarco', 'Talca', 'Región del Maule'),
  ('07107', 'Pencahue', 'Talca', 'Región del Maule'),
  ('07108', 'Río Claro', 'Talca', 'Región del Maule'),
  ('07109', 'San Clemente', 'Talca', 'Región del Maule'),
  ('07110', 'San Rafael', 'Talca', 'Región del Maule'),
  ('07201', 'Cauquenes', 'Cauquenes', 'Región del Maule'),
  ('07202', 'Chanco', 'Cauquenes', 'Región del Maule'),
  ('07203', 'Pelluhue', 'Cauquenes', 'Región del Maule'),
  ('07301', 'Curicó', 'Curicó', 'Región del Maule'),
  ('07302', 'Hualañé', 'Curicó', 'Región del Maule'),
  ('07303', 'Licantén', 'Curicó', 'Región del Maule'),
  ('07304', 'Molina', 'Curicó', 'Región del Maule'),
  ('07305', 'Rauco', 'Curicó', 'Región del Maule'),
  ('07306', 'Romeral', 'Curicó', 'Región del Maule'),
  ('07307', 'Sagrada Familia', 'Curicó', 'Región del Maule'),
  ('07308', 'Teno', 'Curicó', 'Región del Maule'),
  ('07309', 'Vichuquén', 'Curicó', 'Región del Maule'),
  ('07401', 'Linares', 'Linares', 'Región del Maule'),
  ('07402', 'Colbún', 'Linares', 'Región del Maule'),
  ('07403', 'Longaví', 'Linares', 'Región del Maule'),
  ('07404', 'Parral', 'Linares', 'Región del Maule'),
  ('07405', 'Retiro', 'Linares', 'Región del Maule'),
  ('07406', 'San Javier', 'Linares', 'Región del Maule'),
  ('07407', 'Villa Alegre', 'Linares', 'Región del Maule'),
  ('07408', 'Yerbas Buenas', 'Linares', 'Región del Maule'),
  ('bi0101', 'Concepción', 'Concepción', 'Región del Biobío'),
  ('08102', 'Coronel', 'Concepción', 'Región del Biobío'),
  ('08103', 'Chiguayante', 'Concepción', 'Región del Biobío'),
  ('08104', 'Florida', 'Concepción', 'Región del Biobío'),
  ('08105', 'Hualqui', 'Concepción', 'Región del Biobío'),
  ('08106', 'Lota', 'Concepción', 'Región del Biobío'),
  ('08107', 'Penco', 'Concepción', 'Región del Biobío'),
  ('08108', 'San Pedro de la Paz', 'Concepción', 'Región del Biobío'),
  ('08109', 'Santa Juana', 'Concepción', 'Región del Biobío'),
  ('08110', 'Talcahuano', 'Concepción', 'Región del Biobío'),
  ('08111', 'Tomé', 'Concepción', 'Región del Biobío'),
  ('08112', 'Hualpén', 'Concepción', 'Región del Biobío'),
  ('08201', 'Lebu', 'Arauco', 'Región del Biobío'),
  ('08202', 'Arauco', 'Arauco', 'Región del Biobío'),
  ('08203', 'Cañete', 'Arauco', 'Región del Biobío'),
  ('08204', 'Contulmo', 'Arauco', 'Región del Biobío'),
  ('08205', 'Curanilahue', 'Arauco', 'Región del Biobío'),
  ('08206', 'Los Álamos', 'Arauco', 'Región del Biobío'),
  ('08207', 'Tirúa', 'Arauco', 'Región del Biobío'),
  ('08301', 'Los Ángeles', 'Biobío', 'Región del Biobío'),
  ('08302', 'Antuco', 'Biobío', 'Región del Biobío'),
  ('08303', 'Cabrero', 'Biobío', 'Región del Biobío'),
  ('08304', 'Laja', 'Biobío', 'Región del Biobío'),
  ('08305', 'Mulchén', 'Biobío', 'Región del Biobío'),
  ('08306', 'Nacimiento', 'Biobío', 'Región del Biobío'),
  ('08307', 'Negrete', 'Biobío', 'Región del Biobío'),
  ('08308', 'Quilaco', 'Biobío', 'Región del Biobío'),
  ('08309', 'Quilleco', 'Biobío', 'Región del Biobío'),
  ('08310', 'San Rosendo', 'Biobío', 'Región del Biobío'),
  ('08311', 'Santa Bárbara', 'Biobío', 'Región del Biobío'),
  ('08312', 'Tucapel', 'Biobío', 'Región del Biobío'),
  ('08313', 'Yumbel', 'Biobío', 'Región del Biobío'),
  ('08314', 'Alto Biobío', 'Biobío', 'Región del Biobío'),
  ('08401', 'Chillán', 'Ñuble', 'Región de Ñuble'),
  ('08402', 'Bulnes', 'Ñuble', 'Región de Ñuble'),
  ('08403', 'Cobquecura', 'Ñuble', 'Región de Ñuble'),
  ('08404', 'Coelemu', 'Ñuble', 'Región de Ñuble'),
  ('08405', 'Coihueco', 'Ñuble', 'Región de Ñuble'),
  ('08406', 'Chillán Viejo', 'Ñuble', 'Región de Ñuble'),
  ('08407', 'El Carmen', 'Ñuble', 'Región de Ñuble'),
  ('08408', 'Ninhue', 'Ñuble', 'Región de Ñuble'),
  ('08409', 'Ñiquén', 'Ñuble', 'Región de Ñuble'),
  ('08410', 'Pemuco', 'Ñuble', 'Región de Ñuble'),
  ('08411', 'Pinto', 'Ñuble', 'Región de Ñuble'),
  ('08412', 'Portezuelo', 'Ñuble', 'Región de Ñuble'),
  ('08413', 'Quillón', 'Ñuble', 'Región de Ñuble'),
  ('08414', 'Quirihue', 'Ñuble', 'Región de Ñuble'),
  ('08415', 'Ránquil', 'Ñuble', 'Región de Ñuble'),
  ('08416', 'San Carlos', 'Ñuble', 'Región de Ñuble'),
  ('08417', 'San Fabián', 'Ñuble', 'Región de Ñuble'),
  ('08418', 'San Ignacio', 'Ñuble', 'Región de Ñuble'),
  ('08419', 'San Nicolás', 'Ñuble', 'Región de Ñuble'),
  ('08420', 'Treguaco', 'Ñuble', 'Región de Ñuble'),
  ('08421', 'Yungay', 'Ñuble', 'Región de Ñuble'),
  ('ar0101', 'Temuco', 'Cautín', 'Región de la Araucanía'),
  ('09102', 'Carahu', 'Cautín', 'Región de la Araucanía'),
  ('09103', 'Cunco', 'Cautín', 'Región de la Araucanía'),
  ('09104', 'Curarrehue', 'Cautín', 'Región de la Araucanía'),
  ('09105', 'Freire', 'Cautín', 'Región de la Araucanía'),
  ('09106', 'Galvarin', 'Cautín', 'Región de la Araucanía'),
  ('09107', 'Gorbea', 'Cautín', 'Región de la Araucanía'),
  ('09108', 'Lautaro', 'Cautín', 'Región de la Araucanía'),
  ('09109', 'Loncoche', 'Cautín', 'Región de la Araucanía'),
  ('09110', 'Melipeuco', 'Cautín', 'Región de la Araucanía'),
  ('09111', 'Nueva Imperial', 'Cautín', 'Región de la Araucanía'),
  ('09112', 'Padre Las Casas', 'Cautín', 'Región de la Araucanía'),
  ('09113', 'Perquenco', 'Cautín', 'Región de la Araucanía'),
  ('09114', 'Pitrufquén', 'Cautín', 'Región de la Araucanía'),
  ('09115', 'Pucón', 'Cautín', 'Región de la Araucanía'),
  ('09116', 'Saavedra', 'Cautín', 'Región de la Araucanía'),
  ('09117', 'Teodoro Schmidt', 'Cautín', 'Región de la Araucanía'),
  ('09118', 'Toltén', 'Cautín', 'Región de la Araucanía'),
  ('09119', 'Vilcún', 'Cautín', 'Región de la Araucanía'),
  ('09120', 'Villarrica', 'Cautín', 'Región de la Araucanía'),
  ('09121', 'Cholchol', 'Cautín', 'Región de la Araucanía'),
  ('09201', 'Angol', 'Malleco', 'Región de la Araucanía'),
  ('09202', 'Collipulli', 'Malleco', 'Región de la Araucanía'),
  ('09203', 'Curacautín', 'Malleco', 'Región de la Araucanía'),
  ('09204', 'Ercilla', 'Malleco', 'Región de la Araucanía'),
  ('09205', 'Lonquimay', 'Malleco', 'Región de la Araucanía'),
  ('09206', 'Los Sauces', 'Malleco', 'Región de la Araucanía'),
  ('09207', 'Lumaco', 'Malleco', 'Región de la Araucanía'),
  ('09208', 'Purén', 'Malleco', 'Región de la Araucanía'),
  ('09209', 'Renaico', 'Malleco', 'Región de la Araucanía'),
  ('09210', 'Traiguén', 'Malleco', 'Región de la Araucanía'),
  ('09211', 'Victoria', 'Malleco', 'Región de la Araucanía'),
  ('lr0101', 'Valdivia', 'Valdivia', 'Región de Los Ríos'),
  ('14102', 'Corral', 'Valdivia', 'Región de Los Ríos'),
  ('14103', 'Lanco', 'Valdivia', 'Región de Los Ríos'),
  ('14104', 'Los Lagos', 'Valdivia', 'Región de Los Ríos'),
  ('14105', 'Máfil', 'Valdivia', 'Región de Los Ríos'),
  ('14106', 'Mariquina', 'Valdivia', 'Región de Los Ríos'),
  ('14107', 'Paillaco', 'Valdivia', 'Región de Los Ríos'),
  ('14108', 'Panguipulli', 'Valdivia', 'Región de Los Ríos'),
  ('14201', 'La Unión', 'Ranco', 'Región de Los Ríos'),
  ('14202', 'Futrono', 'Ranco', 'Región de Los Ríos'),
  ('14203', 'Lago Ranco', 'Ranco', 'Región de Los Ríos'),
  ('14204', 'Río Bueno', 'Ranco', 'Región de Los Ríos'),
  ('ll0101', 'Puerto Montt', 'Llanquihue', 'Región de Los Lagos'),
  ('10102', 'Calbuco', 'Llanquihue', 'Región de Los Lagos'),
  ('10103', 'Cochamó', 'Llanquihue', 'Región de Los Lagos'),
  ('10104', 'Fresia', 'Llanquihue', 'Región de Los Lagos'),
  ('10105', 'Frutillar', 'Llanquihue', 'Región de Los Lagos'),
  ('10106', 'Los Muermos', 'Llanquihue', 'Región de Los Lagos'),
  ('10107', 'Llanquihue', 'Llanquihue', 'Región de Los Lagos'),
  ('10108', 'Maullín', 'Llanquihue', 'Región de Los Lagos'),
  ('10109', 'Puerto Varas', 'Llanquihue', 'Región de Los Lagos'),
  ('10201', 'Castro', 'Chiloé', 'Región de Los Lagos'),
  ('10202', 'Ancud', 'Chiloé', 'Región de Los Lagos'),
  ('10203', 'Chonchi', 'Chiloé', 'Región de Los Lagos'),
  ('10204', 'Curaco de Vélez', 'Chiloé', 'Región de Los Lagos'),
  ('10205', 'Dalcahue', 'Chiloé', 'Región de Los Lagos'),
  ('10206', 'Puqueldón', 'Chiloé', 'Región de Los Lagos'),
  ('10207', 'Queilén', 'Chiloé', 'Región de Los Lagos'),
  ('10208', 'Quellón', 'Chiloé', 'Región de Los Lagos'),
  ('10209', 'Quemchi', 'Chiloé', 'Región de Los Lagos'),
  ('10210', 'Quinchao', 'Chiloé', 'Región de Los Lagos'),
  ('10301', 'Osorno', 'Osorno', 'Región de Los Lagos'),
  ('10302', 'Puerto Octay', 'Osorno', 'Región de Los Lagos'),
  ('10303', 'Purranque', 'Osorno', 'Región de Los Lagos'),
  ('10304', 'Puyehue', 'Osorno', 'Región de Los Lagos'),
  ('10305', 'Río Negro', 'Osorno', 'Región de Los Lagos'),
  ('10306', 'San Juan de la Costa', 'Osorno', 'Región de Los Lagos'),
  ('10307', 'San Pablo', 'Osorno', 'Región de Los Lagos'),
  ('10401', 'Chaitén', 'Palena', 'Región de Los Lagos'),
  ('10402', 'Futaleufú', 'Palena', 'Región de Los Lagos'),
  ('10403', 'Hualaihué', 'Palena', 'Región de Los Lagos'),
  ('10404', 'Palena', 'Palena', 'Región de Los Lagos'),
  ('11101', 'Coyhaique', 'Coihaique', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11201', 'Lago Verde', 'Coihaique', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11301', 'Aysén', 'Aisén', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11302', 'Cisnes', 'Aisén', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11303', 'Guaitecas', 'Aisén', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11401', 'Cochrane', 'Capitán Pratt', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11402', 'O''Higgins', 'Capitán Pratt', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11403', 'Tortel', 'Capitán Pratt', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11501', 'Chile Chico', 'General Carrera', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('11502', 'Río Ibáñez', 'General Carrera', 'Región Aisén del Gral. Carlos Ibáñez del Campo'),
  ('12101', 'Punta Arenas', 'Magallanes', 'Región de Magallanes y de la Antártica Chilena'),
  ('12102', 'Laguna Blanca', 'Magallanes', 'Región de Magallanes y de la Antártica Chilena'),
  ('12103', 'Río Verde', 'Magallanes', 'Región de Magallanes y de la Antártica Chilena'),
  ('12104', 'San Gregorio', 'Magallanes', 'Región de Magallanes y de la Antártica Chilena'),
  ('12201', 'Cabo de Hornos (Ex. Navarino)', 'Antártica Chilena', 'Región de Magallanes y de la Antártica Chilena'),
  ('12202', 'Antártica', 'Antártica Chilena', 'Región de Magallanes y de la Antártica Chilena'),
  ('12301', 'Porvenir', 'Tierra del Fuego', 'Región de Magallanes y de la Antártica Chilena'),
  ('12302', 'Primavera', 'Tierra del Fuego', 'Región de Magallanes y de la Antártica Chilena'),
  ('12303', 'Timaukel', 'Tierra del Fuego', 'Región de Magallanes y de la Antártica Chilena'),
  ('12401', 'Natales', 'Última Esperanza', 'Región de Magallanes y de la Antártica Chilena'),
  ('12402', 'Torres del Paine', 'Última Esperanza', 'Región de Magallanes y de la Antártica Chilena'),
  ('rm0101', 'Santiago', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13102', 'Cerrillos', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13103', 'Cerro Navia', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13104', 'Conchalí', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13105', 'El Bosque', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0106', 'Estación Central', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13107', 'Huechuraba', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13108', 'Independencia', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13109', 'La Cisterna', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13110', 'La Florida', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13111', 'La Granja', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13112', 'La Pintana', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0113', 'La Reina', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0114', 'Las Condes', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13115', 'Lo Barnechea', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13116', 'Lo Espejo', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13117', 'Lo Prado', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13118', 'Macul', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0119', 'Maipú', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0120', 'Ñuñoa', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13121', 'Pedro Aguirre Cerda', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0122', 'Peñalolén', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0123', 'Providencia', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13124', 'Pudahuel', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13125', 'Quilicura', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13126', 'Quinta Normal', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13127', 'Recoleta', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13128', 'Renca', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13129', 'San Joaquín', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13130', 'San Miguel', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13131', 'San Ramón', 'Santiago', 'Región Metropolitana de Santiago'),
  ('13132', 'Vitacura', 'Santiago', 'Región Metropolitana de Santiago'),
  ('rm0201', 'Puente Alto', 'Cordillera', 'Región Metropolitana de Santiago'),
  ('13202', 'Pirque', 'Cordillera', 'Región Metropolitana de Santiago'),
  ('13203', 'San José de Maipo', 'Cordillera', 'Región Metropolitana de Santiago'),
  ('13301', 'Colina', 'Chacabuco', 'Región Metropolitana de Santiago'),
  ('13302', 'Lampa', 'Chacabuco', 'Región Metropolitana de Santiago'),
  ('13303', 'Tiltil', 'Chacabuco', 'Región Metropolitana de Santiago'),
  ('13401', 'San Bernardo', 'Maipo', 'Región Metropolitana de Santiago'),
  ('13402', 'Buin', 'Maipo', 'Región Metropolitana de Santiago'),
  ('13403', 'Calera de Tango', 'Maipo', 'Región Metropolitana de Santiago'),
  ('13404', 'Paine', 'Maipo', 'Región Metropolitana de Santiago'),
  ('13501', 'Melipilla', 'Mellipilla', 'Región Metropolitana de Santiago'),
  ('13502', 'Alhué', 'Mellipilla', 'Región Metropolitana de Santiago'),
  ('13503', 'Curacaví', 'Mellipilla', 'Región Metropolitana de Santiago'),
  ('13504', 'María Pinto', 'Mellipilla', 'Región Metropolitana de Santiago'),
  ('13505', 'San Pedro', 'Mellipilla', 'Región Metropolitana de Santiago'),
  ('13601', 'Talagante', 'Talagante', 'Región Metropolitana de Santiago'),
  ('13602', 'El Monte', 'Talagante', 'Región Metropolitana de Santiago'),
  ('13603', 'Isla de Maipo', 'Talagante', 'Región Metropolitana de Santiago'),
  ('13604', 'Padre Hurtado', 'Talagante', 'Región Metropolitana de Santiago'),
  ('13605', 'Peñaflor', 'Talagante', 'Región Metropolitana de Santiago')
on conflict (name) do update set
  province = excluded.province,
  region = excluded.region,
  is_active = true;

-- Existing historical rows may be incomplete, but every new write must use a
-- catalog code. Profiles created by Auth are allowed to remain blank until
-- the user completes their profile.
alter table public.profiles
  add constraint profiles_commune_catalog_check
  check (btrim(commune) = '' or commune_code is not null) not valid;

alter table public.matches
  add constraint matches_commune_catalog_check
  check (commune_code is not null) not valid;
